### ISSUE TITLE
Support SQL Server 2016

### ISSUE THREAD

**Issue by martincostello** [martincostello/sqllocaldb#21]
This is a placeholder issue for testing support for SQL Server 2016 LocalDB once a version of it is available for testing.

**Comment by CyberSinh** [comment]
Hi Martin,

SQL Server 2016 LocalDB x64 is available in RC1 at:
https://www.microsoft.com/en-us/evalcenter/evaluate-sql-server-2016

I could send you directly the MSI (44 MB) if you want.

So, feel free to test that version with your project.

**Comment by martincostello** [comment]
Oh great, thanks for letting me know!

I'd been looking for the install package for this for a while, but I must have missed it in the RC1 announcement.

**Comment by martincostello** [comment]
For reference, the MSI is here on the ISO image: ```.\1033_ENU_LP\x64\Setup\x64\SqlLocalDB.msi```.

**Comment by martincostello** [comment]
Testing with SQL Server 2016 RC1 shows no compatibility issues, and the documentation ([here](https://msdn.microsoft.com/en-us/library/hh510202.aspx) and [here](https://msdn.microsoft.com/en-gb/library/hh234692.aspx)) contains no apparent new functionality and/or changes.
