### ISSUE TITLE
Provide package for the .NET 4.x platform (instead of just .NET 3.5 - CLR 2.0)

### ISSUE THREAD

**Issue by CyberSinh** [martincostello/sqllocaldb#22]
.Net 3.5 is even not installed by default in Windows 10. 
.Net 4.x has been released for 5 years now.

**Comment by martincostello** [comment]
This has been the case in the source since 021f438edba6009d23cb9dce24aec7bceee455a3, however there's been no real reason to publish a new version since 1.14.0.

I'll publish 1.15.0 in the next few days.

**Comment by martincostello** [comment]
If you need a .NET 4.0 targeting version ASAP, there's a pre-release package of 1.15.0 you can grab from the [AppVeyor CI](https://ci.appveyor.com/project/martincostello/sqllocaldb/build/artifacts).

**Comment by CyberSinh** [comment]
Thank you. I'm going to wait for the support of SQL Server 2016.

**Comment by CyberSinh** [comment]
Hi, SQL Server 2016 has been released as RTM now. Do you plan to update the official NuGet package soon? Thanks.

**Comment by martincostello** [comment]
Just to clarify, is this to get access to the .NET 4.0 package, or for 2016 support? If the latter then all versions of the library that support SQL Server LocalDB 2014 support it. If the former I'll look at pushing the package today or tomorrow when I have some time spare.

**Comment by CyberSinh** [comment]
Both. I expect an official support for SQL Server 2016 and a .NET 4.x package. I understood you were waiting for the release of the RTM version of SQL Server 2016 to update your NuGet package to 1.15.

**Comment by martincostello** [comment]
I'll push the package when I get the chance to release .NET 4.0 support since you're asking for it. Otherwise I was waiting _in case_ I needed to make changes to support 2016. It turned out in testing no changes were required, so 1.14 already supports 2016, just for .NET 3.5. Otherwise there's nothing really compelling the release of 1.15.

**Comment by martincostello** [comment]
Release should be available in an hour or so. CI troubles.

**Comment by martincostello** [comment]
Resolved by [v1.15.0.0](https://github.com/martincostello/sqllocaldb/releases/tag/v1.15.0.0)
