### ISSUE TITLE
Rename namespace from System.

### ISSUE THREAD

**Issue by DustinVenegas** [martincostello/sqllocaldb#27]
System is a reserved namespace and should not be used. I recommend using SqlLocalDb or MartinCostello instead.

**Comment by martincostello** [comment]
The namespace was originally chosen to sit within ```System.Data```, like other non-Microsoft ADO.NET components chose to do so (for example [SQLite](https://system.data.sqlite.org/index.html/doc/trunk/www/index.wiki)).

Given that this would be a massive breaking interface change, this will not be done.
