### ISSUE TITLE
Return values

### ISSUE THREAD

**Issue by regattamaster** [martincostello/sqllocaldb#28]
How does one get the return values from a call to the API?  For instance, sqllocaldbapi.ShareInstance(dbInstance, dbSharedInstance) fails but does not return an error.

**Comment by martincostello** [comment]
Could you give a bit more detail about how it is failing? Any non-zero return code from the SQL Instance API method for sharing should [cause an exception to be thrown](https://github.com/martincostello/sqllocaldb/blob/master/src/SqlLocalDb/SqlLocalDbApi.cs#L683-L686).

You can turn on logging to see what's happening under the hood like this:

```xml
<system.diagnostics>
  <sharedListeners>
    <add name="Console" type="System.Diagnostics.ConsoleTraceListener" />
  </sharedListeners>
  <sources>
    <source name="System.Data.SqlLocalDb">
      <listeners>
        <add name="Console" />
      </listeners>
    </source>
  </sources>
  <switches>
    <add name="System.Data.SqlLocalDb" value="Verbose" />
  </switches>
  <trace autoflush="true" />
</system.diagnostics>
```

You should get output similar to this:

```cmd
2016-12-07 10:15:49,743 DEBUG System.Data.SqlLocalDb - Sharing SQL LocalDB instance '{Name}' for owner SID '{SID}'. Shared instance name: '{SharedName}'.
2016-12-07 10:15:49,745 DEBUG System.Data.SqlLocalDb - Shared SQL LocalDB instance '{Name}' for owner SID '{SID}' as '{SharedName}'.
2016-12-07 10:15:50,042 DEBUG System.Data.SqlLocalDb - Stopping sharing SQL LocalDB instance '{Name}'.
2016-12-07 10:15:50,043 DEBUG System.Data.SqlLocalDb - Stopped sharing SQL LocalDB instance '{Name}'.
```

**Comment by regattamaster** [comment]
Hi, Martin
Thank you for the quick response, and an apology for jumping to conclusions.  The function actually did not fail, as it turns out, but I could not find how to get a return value to see what it did.  When I run the command line tool as a process, I can see what happens when I run the commands.

So in code (this is VB, sorry), I would like to be able to get a return code or value so I can determine whether to do other commands or abort (for instance):

Dim pOK as Boolean = False
pOK = SqlLocalDbApi.ShareInstance(dbInstance, dbSharedInstance)
If pOK = true then …

I’m not enough of a programmer to look to deeply under the hood, plus I don’t work in C#.

Your API wrapper, by the way, is a great tool – thanks!

Steve

**Comment by martincostello** [comment]
@regattamaster I'd suggest an approach similar to the snippet below by catching ```SqlLocalDbException``` which is thrown if the operation is not successful, and then inspecting its ```ErrorCode``` property. You can use the constants in the ```SqlLocalDbErrors``` class to compare against specific errors that you want to ignore/handle.

```vb
Imports System.Data.SqlLocalDb

Friend Module Program

    Friend Sub Main()

        Dim dbInstance As String = "MyName"
        Dim dbSharedInstance As String = "MySharedName"

        Try
            ' Try to share the instance
            SqlLocalDbApi.ShareInstance(dbInstance, dbSharedInstance)

        Catch ex As SqlLocalDbException

            ' Inspect the ErrorCode associated with the exception against the SQL LocalDB error codes
            If (ex.ErrorCode <> SqlLocalDbErrors.AdminRightsRequired) Then

                ' Do something with the errors you are or are not interested in
                Throw

            End If

        End Try

    End Sub

End Module
```

**Comment by regattamaster** [comment]
Excellent – thanks very much!

**Comment by martincostello** [comment]
@regattamaster No problem - are you happy with me closing this issue?

**Comment by regattamaster** [comment]
Yes.
