### ISSUE TITLE
Support a way to parse LocalDB specific properties from connection string

### ISSUE THREAD

**Issue by JackUkleja** [martincostello/sqllocaldb#31]
The standard .NET `SqlConnectionStringBuilder` is unaware of a few "properties" that are specific to SQL LocalDB:

* IsLocalDb
* InstanceName
* IsSharedInstance
* others relating to named pipes etc?

Would be great if the following connection string "(localdb)\MyInstance" could be resolved to `IsLocalDb = true`, and `InstanceName = MyInstance`.

**Comment by martincostello** [comment]
Interesting. I've not seen these before. Do you have a link to some documentation where these extra properties are described?

**Comment by JackUkleja** [comment]
Sorry what I wrote was confusing. These are the "properties" I've dreamed up that I would like to see supported on some sort of enhanced `SqlConnectionStringBuilder`. So as of yet they don't exist, but that's what I would like to be able to do just like I can access the similar properties on a `SqlConnectionStringBuilder`.

**Comment by martincostello** [comment]
Ah, I see. I'll have a think about whether this would be easy to achieve with a custom connection string builder without causing any incompatibility issues with the existing type. Alternatively, it could be some extension methods to the connection string builder instead.

**Comment by martincostello** [comment]
Well it definitely can't be a derived class of ```SqlConnectionStringBuilder``` as it is marked as ```sealed```.

**Comment by martincostello** [comment]
I'm not sure what value this would add due to the need for it to be a custom connection string as SQL's is sealed, so existing code wouldn't really be able to interop with it and understand it.

If there's some more concrete examples of how this could be used, then maybe this can be looked at again for after `2.0.0` is released.
