### ISSUE TITLE
Backup Database

### ISSUE THREAD

**Issue by ghost1372** [martincostello/sqllocaldb#34]
hi can i use this library for backup and restore my sql localdb 2016 ?

**Comment by martincostello** [comment]
No, there is no functionality to do that in the SQL LocalDB Instance API.

**Comment by ghost1372** [comment]
can you add this API?

**Comment by martincostello** [comment]
The SQL LocalDB Instance API is provided by Microsoft, this project just wraps it for use with .NET. I can't add new functionality to Microsoft's LocalDB API.
