### ISSUE TITLE
Attach DBs to an Instance

### ISSUE THREAD

**Issue by wiseeker** [martincostello/sqllocaldb#38]
Hello,
Thank you for this useful library.

In my case, I would have mdf/ldf files in a pre-determined location. I would like to do GetOrCreateInstance() and then I would like to attach mdf files to this instance. How do I do this?

**Comment by martincostello** [comment]
I _think_ there’s a way to do this, but I’m a bit rusty. I’ll try and cook up a code sample for you for this scenario tomorrow.

**Comment by wiseeker** [comment]
Thank you for your quick response. For now, I'm moving forward with T-SQL `CREATE DATABASE <db> ON (FILENAME = <path>) FOR ATTACH;` syntax.

**Comment by martincostello** [comment]
That sounds like what I was thinking off, so I'll just mark this as closed.
