### ISSUE TITLE
Update Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by MattBussing** [martincostello/sqllocaldb#440]
Can you update this library to use the latest of Microsoft.Data.SqlClient please?

https://www.nuget.org/packages/Microsoft.Data.SqlClient/

**Comment by martincostello** [comment]
The library intentionally uses the lowest-common-denominator version as the referenced version to make it usable to as wide a range of projects as possible.

What specific benefit would you expect to gain by having this library reference 3.0.0 vs. you referencing it yourself in the project you're using this library with?

**Comment by martincostello** [comment]
That just sounds like standard .NET Framework behaviour for handling binding redirects when different parts of the dependency tree rely on different versions of the same assembly.

The library could be updated to the latest version, and then six months later there's a new update and something else updates and then you're back with the same problem again until everything in your tree updates to the latest version.

**Comment by Cjewett** [comment]
Was able to get this working with proper binding redirects. Can understand the decision to keep them on lowest common denominator, just a pain in .NET Framework world.

**Comment by martincostello** [comment]
Will revisit the minimum version in future releases, but for now there is no compelling reason to update the library to reference a newer version.
