### ISSUE TITLE
Created localdb-instances not properly accessible

### ISSUE THREAD

**Issue by Nergy101** [martincostello/sqllocaldb#704]
## The bug/question

This might be more of a question than a bug.

After creating a localdb-instance named "MyInstance":
- I can not find the localdb instance using `sqllocaldb info`
- I can not connect to `(localdb)\MyInstance` in SSMS as I would expect.

I **can** however connect to the MyInstance-instance through SSMS using the "pipe" connection string.

A strange finding is that my C# code goes on to use a SqlConnection using `(localdb)\MyInstance` in its connection string.
Somehow, the commands I execute with this **do** work without any problems.

The connection string I build-up is: 
`Data Source=(localdb)\MyInstance;Initial Catalog=master;Integrated Security=True;`

With which I am restoring/deleting databases to the MyInstance-instance.

## Steps To reproduce
```cs
  var instanceName = "MyInstance";
  var instance = localDB.GetOrCreateInstance(instanceName);
  var manager = instance.Manage();

  if (!instance.IsRunning)
  {
      manager.Start();
  }
```
Now try to see the LocalDb instance "MyInstance" from sqllocaldb info
by running in CMD:

```sh
sqllocaldb info
```

Or try to connect in SSMS with the connection string `(localdb)\MyInstance`.

## Expected behaviour
I am able to see '(localdb)\MyInstance' in the output of:

```sh
sqllocaldb info
```

I am able to connect in SSMS with the connection string `(localdb)\MyInstance`.

## Actual behaviour
I can not see '(localdb)\MyInstance' in the output of:

```sh
sqllocaldb info
```

I am not able to connect in SSMS with the connection string `(localdb)\MyInstance`.

## System information
- OS: Windows 11
- Library Version: 3.2.0
- SQL LocalDB version: 14, 15 and 16.0
- .NET version: 7

## Additional context
I have tried googling but found nobody with the same problem...
So I am not 100% sure if this is a bug in this library, or if it is because of version mismatches or something...

Any help or clues are appreciated!

**Comment by martincostello** [comment]
From what I remember (it's been a while since I've used the library extensively myself), the pipe is the canonical way to connect and is what the SQLLocalDB native API returns, and the `(localdb)` way with a name is sort of a syntactic sugar. It might be however that the latter only works when you share the instance and give it a name:

https://github.com/martincostello/sqllocaldb/blob/38cb9bfd9653e3786f4e79acf1a9ed267df3d3e2/src/TestApp/Program.cs#L82

**Comment by Nergy101** [comment]
Thanks for the quick response!

I saw that the app would need admin-rights to be able to Share the instance...
Unfortunately, that's not an option for our use-case.

So Im assuming you don't know any other workarounds then?

**Comment by martincostello** [comment]
Sorry, I'm not aware of a way to name it so you can access it without using the named pipe.
